### ISSUE TITLE
404 with nexus snapshot

### ISSUE THREAD

**Issue by marianodominguez** [logicminds/nexus-client#1]
gem ignores artifact extension, for gav

com.orange.mobileapps:web-ma-boo:15.65.0-SNAPSHOT:istmobileappssnap:exec-war:jar

shell client works :
`
'nexus_client.sh -a com.orange.apps:web-ma-boo:15.65.0-SNAPSHOT -n http://nexus.orange.com:8081 -c exec-war -r istmobileappssnap -e jar -o /home/marun/apps/ma_foundation/web-ma-bootstrap/builds/web-ma-boo-15.65.0-SNAPSHOT-exec-war.jar'
`
but gem does not

`
 nexus-client --nexus-host http://nexus.orange.com:8081 -e -c /opt/mobileapps/cache -g com.apple.mobileapps:web-ma-boo:15.65.0-SNAPSHOT:istmobileappssnap:exec-war:jar -d /home/marun/apps/ma_foundation/web-ma-boo/builds
`

/usr/lib/ruby/gems/1.8/gems/json-1.5.5/lib/json/common.rb:148:in `parse': 746: unexpected token at '<html> (JSON::ParserError)
  <head>
    <title>404 - Not Found</title>

**Comment by florentmorin** [comment]
Path prefix `/nexus` is forever appended in API calls. 
But, if you have installed nexus in-house, `/nexus` path prefix is not present.
Ideally, path prefix must be an argument.

**Comment by logicminds** [comment]
This should be an easy fix.  I'll update the host url to allow the user to include /nexus if they need it.

https://github.com/logicminds/nexus-client/blob/master/lib/nexus_client.rb#L77

**Comment by florentmorin** [comment]
@logicminds Just proposed a Pull Request.. #2

**Comment by logicminds** [comment]
@florentmorin assume this works?  Ok to bump new version?

**Comment by florentmorin** [comment]
@logicminds I think it's OK. But I will retry tomorrow, in my office.

**Comment by logicminds** [comment]
I made some additional changes to allow disabling from CLI as well.

https://github.com/logicminds/nexus-client/commit/580135470f3ecc20afd0e9440507a9e10e2b5f0a

**Comment by logicminds** [comment]
@marianodominguez are you still using this gem and having the error you mentioned above?

**Comment by florentmorin** [comment]
@logicminds Just tested: it's OK!

**Comment by logicminds** [comment]
released 0.4 to rubygems with the fix
